from __future__ import annotations

import argparse
import re
import shutil
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path


MARKER_FILE = ".m2-obsidian-export"
INVALID_NAME_RE = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
NAME_TRANSLATION = str.maketrans({
    "/": "／",
    "\\": "＼",
    ":": "：",
    "|": "｜",
    "?": "？",
    "*": "＊",
    "\"": "＂",
    "<": "＜",
    ">": "＞",
})


@dataclass
class TreeNode:
    title: str
    depth: int = 0
    parent: TreeNode | None = None
    children: list[TreeNode] = field(default_factory=list)
    folder_name: str = ""
    note_path: Path | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate an Obsidian markdown graph vault from a FreeMind .mm file."
    )
    parser.add_argument("input_mm", type=Path, help="Path to the source .mm file")
    parser.add_argument("output_dir", type=Path, help="Target directory for the Obsidian vault")
    return parser.parse_args()


def sanitize_name(value: str) -> str:
    cleaned = (value or "").strip() or "未命名节点"
    cleaned = cleaned.translate(NAME_TRANSLATION)
    cleaned = INVALID_NAME_RE.sub("_", cleaned)
    cleaned = cleaned.rstrip(" .")
    return cleaned[:120] or "未命名节点"


def build_tree(element: ET.Element, parent: TreeNode | None = None, depth: int = 0) -> TreeNode:
    node = TreeNode(
        title=(element.attrib.get("TEXT") or "").strip() or "未命名节点",
        depth=depth,
        parent=parent,
    )
    node.children = [build_tree(child, node, depth + 1) for child in element.findall("node")]
    return node


def parse_mm(path: Path) -> TreeNode:
    root = ET.parse(path).getroot().find("node")
    if root is None:
        raise ValueError(f"No root <node> found in {path}")
    return build_tree(root)


def prepare_output_dir(output_dir: Path) -> None:
    marker = output_dir / MARKER_FILE
    if output_dir.exists():
        if marker.exists():
            shutil.rmtree(output_dir)
        else:
            raise RuntimeError(
                f"Refusing to overwrite non-generated directory: {output_dir}"
            )
    output_dir.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by generate_obsidian_graph_from_mm.py\n", encoding="utf-8")


def assign_note_paths(node: TreeNode, parent_dir: Path) -> None:
    sibling_counts: dict[str, int] = {}
    for child in node.children:
        base_name = sanitize_name(child.title)
        sibling_counts[base_name] = sibling_counts.get(base_name, 0) + 1
        suffix = sibling_counts[base_name]
        folder_name = base_name if suffix == 1 else f"{base_name} {suffix}"
        child.folder_name = folder_name
        child_dir = parent_dir / folder_name
        child_dir.mkdir(parents=True, exist_ok=True)
        child.note_path = child_dir / f"{folder_name}.md"
        assign_note_paths(child, child_dir)


def wiki_link(output_dir: Path, note_path: Path | None) -> str:
    if note_path is None:
        return "无"
    relative = note_path.relative_to(output_dir).with_suffix("")
    return f"[[{relative.as_posix()}]]"


def describe_path(node: TreeNode) -> str:
    parts: list[str] = []
    current: TreeNode | None = node
    while current is not None:
        parts.append(current.title)
        current = current.parent
    return " > ".join(reversed(parts))


def join_links(links: list[str]) -> str:
    return "、".join(links) if links else "无"


def render_note(node: TreeNode, output_dir: Path) -> str:
    parent_link = wiki_link(output_dir, node.parent.note_path if node.parent else None)
    child_links = [wiki_link(output_dir, child.note_path) for child in node.children]
    siblings = []
    if node.parent is not None:
        siblings = [
            wiki_link(output_dir, sibling.note_path)
            for sibling in node.parent.children
            if sibling is not node
        ]

    lines = [
        "---",
        "tags:",
        "  - M2",
        "  - 结构图",
        "  - ObsidianGraph",
        f"depth: {node.depth}",
        "---",
        "",
        f"# {node.title}",
        "",
        f"- 上级节点：{parent_link}",
        f"- 下级节点：{join_links(child_links)}",
        f"- 同级节点：{join_links(siblings)}",
        f"- 结构路径：{describe_path(node)}",
        "",
        "## 说明",
        "",
        "这是从 M2 结构图自动导出的 Obsidian 图谱节点。",
    ]
    return "\n".join(lines) + "\n"


def write_tree_notes(node: TreeNode, output_dir: Path) -> int:
    if node.note_path is None:
        raise RuntimeError(f"note_path is missing for node: {node.title}")

    node.note_path.write_text(render_note(node, output_dir), encoding="utf-8")
    written = 1
    for child in node.children:
        written += write_tree_notes(child, output_dir)
    return written


def write_index(output_dir: Path, root: TreeNode) -> None:
    child_links = [wiki_link(output_dir, child.note_path) for child in root.children]
    index_path = output_dir / "索引.md"
    lines = [
        "# M2 Obsidian 图谱入口",
        "",
        "把当前目录作为 Obsidian 仓库打开后，可直接查看关系图谱。",
        "",
        f"- 根节点：{wiki_link(output_dir, root.note_path)}",
        f"- 一级分支：{join_links(child_links)}",
        "",
        "## 用法",
        "",
        "1. 在 Obsidian 中打开本目录。",
        "2. 进入 Graph View 查看整张结构关系图。",
        "3. 从索引或根节点开始浏览各层级参数。",
    ]
    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    root = parse_mm(args.input_mm)

    prepare_output_dir(args.output_dir)

    root.folder_name = sanitize_name(root.title)
    root_dir = args.output_dir / root.folder_name
    root_dir.mkdir(parents=True, exist_ok=True)
    root.note_path = root_dir / f"{root.folder_name}.md"

    assign_note_paths(root, root_dir)
    total_notes = write_tree_notes(root, args.output_dir)
    write_index(args.output_dir, root)

    print(f"generated {total_notes + 1} markdown files in {args.output_dir}")


if __name__ == "__main__":
    main()