md C:\Z\杂项\桌面杂项
move "*.jpg" "C:\Z\杂项\桌面杂项"
move "*.jpeg" "C:\Z\杂项\桌面杂项"
move "*.dwg" "C:\Z\杂项\桌面杂项"
move "*.dwf" "C:\Z\杂项\桌面杂项"
move "*.dxf" "C:\Z\杂项\桌面杂项"
move "*.txt" "C:\Z\杂项\桌面杂项"
move "*.tif" "C:\Z\杂项\桌面杂项"
move "*.psd" "C:\Z\杂项\桌面杂项"
move "*.png" "C:\Z\杂项\桌面杂项"
move "*.gif" "C:\Z\杂项\桌面杂项"
move "*.swf" "C:\Z\杂项\桌面杂项"
move "*.torrent" "C:\Z\杂项\桌面杂项"
move "*.zip" "C:\Z\杂项\桌面杂项"
move "*.7z" "C:\Z\杂项\桌面杂项"
move "*.cdr" "C:\Z\杂项\桌面杂项"
move "*.exe" "C:\Z\杂项\桌面杂项"
move "*.rar" "C:\Z\杂项\桌面杂项"
move "*.pdf" "C:\Z\杂项\桌面杂项"
move "*.obj" "C:\Z\杂项\桌面杂项"
move "*.3ds" "C:\Z\杂项\桌面杂项"
move "*.vrmesh" "C:\Z\杂项\桌面杂项"
move "*.iso" "C:\Z\杂项\桌面杂项"
move "*.mp4" "C:\Z\杂项\桌面杂项"
move "*.m4a" "C:\Z\杂项\桌面杂项"
move "*.mid" "C:\Z\杂项\桌面杂项"
move "*.gp5" "C:\Z\杂项\桌面杂项"
move "*.gp4" "C:\Z\杂项\桌面杂项"
move "*.gp3" "C:\Z\杂项\桌面杂项"
move "*.gpx" "C:\Z\杂项\桌面杂项"
move "*.kbdx" "C:\Z\杂项\桌面杂项"
move "*.xmind" "C:\Z\杂项\桌面杂项"
move "*.xlsx" "C:\Z\杂项\桌面杂项"
move "*.pptx" "C:\Z\杂项\桌面杂项"
move "*.MAX" "C:\Z\杂项\桌面杂项"
move "*.hdr" "C:\Z\杂项\桌面杂项"
move "*.fbx" "C:\Z\杂项\桌面杂项"
move "*.3ds" "C:\Z\杂项\桌面杂项"
move "*.skp" "C:\Z\杂项\桌面杂项"
move "*.ai" "C:\Z\杂项\桌面杂项"
move "*.skb" "C:\Z\杂项\桌面杂项"
move "*.xls" "C:\Z\杂项\桌面杂项"
move "*.fas" "C:\Z\杂项\桌面杂项"
move "*.dwl2" "C:\Z\杂项\桌面杂项"
move "*.vlx" "C:\Z\杂项\桌面杂项"
move "*.exr" "C:\Z\杂项\桌面杂项"
move "*.dat" "C:\Z\杂项\桌面杂项"
move "*.3dm" "C:\Z\杂项\桌面杂项"
move "*.rmvb" "C:\Z\杂项\桌面杂项"
move "*.torrent" "C:\Z\杂项\桌面杂项"
move "*.mkv" "C:\Z\杂项\桌面杂项"
move "*.C4D" "C:\Z\杂项\桌面杂项"
move "*.AVI" "C:\Z\杂项\桌面杂项"
move "*.MP3" "C:\Z\杂项\桌面杂项"
move "*.WAV" "C:\Z\杂项\桌面杂项"
move "*.WEBP" "C:\Z\杂项\桌面杂项"
move "*.stpbak" "C:\Z\杂项\桌面杂项"
move "*.stp" "C:\Z\杂项\桌面杂项"
move "*.ini" "C:\Z\杂项\桌面杂项"
move "*.GH" "C:\Z\杂项\桌面杂项"
move "*.HTM" "C:\Z\杂项\桌面杂项"
move "*.dae" "C:\Z\杂项\桌面杂项"
move "*.mtl" "C:\Z\杂项\桌面杂项"
move "*.blend" "C:\Z\杂项\桌面杂项"
move "*.aep" "C:\Z\杂项\桌面杂项"
move "*.abc" "C:\Z\杂项\桌面杂项"
del "*.dwl" 
del "*.bak"
del "*.log"
del "*.downloading"
del "*.ipa"
del "*.PART"
del "*.php"
del "*.3dmbak"
del "*.rhl"
